# Generated by Django 2.0.13 on 2019-06-25 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Name')),
                ('local', models.TextField(verbose_name='Location')),
                ('imagem', models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Image')),
                ('vagas', models.TextField(verbose_name='Jobs Open')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='artes',
            name='descricao',
            field=models.TextField(verbose_name='Discription'),
        ),
        migrations.AlterField(
            model_name='artes',
            name='imagem',
            field=models.ImageField(blank=True, default=None, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artes',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
